kind: Service
apiVersion: v1
metadata:
  name: interns-backend-service
  labels:
    app: interns-backend-api
spec:
  selector:
    app: interns-backend-api
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
